ros2_videostreamer:
    rtsp_node:
        ros__parameters:
            param_rtsp_uri: "rtsp://admin:admin@192.168.1.108:554/cam/realmonitor?channel=1&subtype=2"
    usb_node:
        ros__parameters:
            param_usb_uri: "/dev/video0"